Trying to fix the known_hosts step

diff --git a/.github/workflows/push-on-main.yml b/.github/workflows/push-on-main.yml
--- a/.github/workflows/push-on-main.yml
+++ b/.github/workflows/push-on-main.yml
@@ -11,8 +11,12 @@ jobs:
     steps:
     - name: Add remote to known_hosts
       run: |
-        #!/bin/bash
-        set -ex
+        #!/usr/bin/env bash
+        # fail if any commands fails
+        set -e
+        # debug log
+        set -x
+
         for ip in $(dig @8.8.8.8 jsorge.net +short); do ssh-keyscan jsorge.net,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
     - name: Set up SSH agent
       uses: webfactory/ssh-agent@v0.5.3
